install.packages('tidyverse', quietly = TRUE,
                 repos =  'https://www.stats.bris.ac.uk/R/')
install.packages('readxl', quietly = TRUE,
                 repos =  'https://www.stats.bris.ac.uk/R/')
install.packages('Hmisc', quietly = TRUE,
                 repos =  'https://www.stats.bris.ac.uk/R/')
install.packages('knitr', quietly = TRUE,
                 repos =  'https://www.stats.bris.ac.uk/R/')
install.packages('scales', quietly = TRUE,
                 repos =  'https://www.stats.bris.ac.uk/R/')
install.packages('lme4', quietly = TRUE,
                 repos =  'https://www.stats.bris.ac.uk/R/')
install.packages('GGally', quietly = TRUE,
                 repos =  'https://www.stats.bris.ac.uk/R/')
install.packages('broom', quietly = TRUE,
                 repos =  'https://www.stats.bris.ac.uk/R/')
install.packages('gtsummary', quietly = TRUE,
                 repos =  'https://www.stats.bris.ac.uk/R/')
